# Generated by Django 4.2 on 2026-01-06 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('sms_type', models.CharField(choices=[('otp', 'OTP Code'), ('verification', 'Verification'), ('alert', 'Alert'), ('reminder', 'Reminder'), ('confirmation', 'Confirmation')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=2)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'db_table': 'sms_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuietHours',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('allow_critical_only', models.BooleanField(default=False, help_text='Allow only critical notifications')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiet_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiet Hours',
                'verbose_name_plural': 'Quiet Hours',
                'db_table': 'quiet_hours',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_otp', models.BooleanField(default=True)),
                ('email_alerts', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('sms_otp', models.BooleanField(default=True)),
                ('sms_alerts', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start', models.TimeField(blank=True, null=True)),
                ('quiet_end', models.TimeField(blank=True, null=True)),
                ('digest_frequency', models.CharField(choices=[('real_time', 'Real-time'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='real_time', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], db_index=True, max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=255)),
                ('delivered', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConsent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('marketing', 'Marketing Emails'), ('security', 'Security Alerts'), ('product_updates', 'Product Updates'), ('newsletter', 'Newsletter'), ('promotions', 'Promotions'), ('analytics', 'Analytics Tracking')], max_length=50)),
                ('is_consented', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('signup', 'Sign Up'), ('settings', 'Settings'), ('email_link', 'Email Link'), ('admin', 'Admin')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Consent',
                'verbose_name_plural': 'Notification Consents',
                'db_table': 'notification_consents',
            },
        ),
        migrations.CreateModel(
            name='NotificationBlocklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_type', models.CharField(choices=[('email', 'Email Address'), ('domain', 'Email Domain'), ('phone', 'Phone Number'), ('sender_id', 'Sender ID (SMS)')], max_length=20)),
                ('blocked_value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('unblocked_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_blocklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Blocklist',
                'verbose_name_plural': 'Notification Blocklists',
                'db_table': 'notification_blocklist',
            },
        ),
        migrations.CreateModel(
            name='MFANotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mfa_type', models.CharField(choices=[('totp_setup', 'TOTP Setup'), ('email_otp', 'Email OTP'), ('sms_otp', 'SMS OTP'), ('backup_code_generation', 'Backup Code Generation'), ('mfa_disabled', 'MFA Disabled'), ('mfa_enabled', 'MFA Enabled'), ('device_verified', 'Device Verified'), ('suspicious_login', 'Suspicious Login')], db_index=True, max_length=50)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('otp_code_hash', models.CharField(blank=True, max_length=255)),
                ('code_length', models.PositiveIntegerField(default=6)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Notification',
                'verbose_name_plural': 'MFA Notifications',
                'db_table': 'mfa_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('email_type', models.CharField(choices=[('otp', 'OTP Code'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('welcome', 'Welcome'), ('account_alert', 'Account Alert'), ('security_alert', 'Security Alert'), ('device_verification', 'Device Verification'), ('session_alert', 'Session Alert'), ('mfa_setup', 'MFA Setup')], db_index=True, max_length=50)),
                ('template_name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetailedNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('otp_email', 'OTP via Email'), ('otp_sms', 'OTP via SMS'), ('login_alert', 'Login Alert'), ('device_added', 'New Device Added'), ('device_verified', 'Device Verified'), ('password_changed', 'Password Changed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('security_alert', 'Security Alert'), ('account_locked', 'Account Locked'), ('failed_login', 'Failed Login Attempts'), ('unusual_activity', 'Unusual Activity'), ('account_recovery', 'Account Recovery'), ('session_expired', 'Session Expired')], max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('respect_quiet_hours', models.BooleanField(default=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Delay notification by minutes')),
                ('max_per_day', models.PositiveIntegerField(default=10, help_text='Max notifications per day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detailed Notification Preference',
                'verbose_name_plural': 'Detailed Notification Preferences',
                'db_table': 'detailed_notification_preferences',
            },
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['user', 'status'], name='sms_notific_user_id_2c9c84_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['sms_type', 'status'], name='sms_notific_sms_typ_8e5ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['-created_at'], name='sms_notific_created_cb6041_idx'),
        ),
        migrations.AddIndex(
            model_name='quiethours',
            index=models.Index(fields=['user', 'day_of_week'], name='quiet_hours_user_id_3676f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quiethours',
            unique_together={('user', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', 'channel'], name='notificatio_user_id_130d18_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['-created_at'], name='notificatio_created_f8e81a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationconsent',
            index=models.Index(fields=['user', 'consent_type'], name='notificatio_user_id_3760ee_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationconsent',
            index=models.Index(fields=['is_consented'], name='notificatio_is_cons_622051_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationconsent',
            unique_together={('user', 'consent_type')},
        ),
        migrations.AddIndex(
            model_name='notificationblocklist',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_5e2964_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationblocklist',
            unique_together={('user', 'block_type', 'blocked_value')},
        ),
        migrations.AddIndex(
            model_name='mfanotification',
            index=models.Index(fields=['user', 'mfa_type', 'is_sent'], name='mfa_notific_user_id_4f60ff_idx'),
        ),
        migrations.AddIndex(
            model_name='mfanotification',
            index=models.Index(fields=['user', 'is_verified'], name='mfa_notific_user_id_b1093c_idx'),
        ),
        migrations.AddIndex(
            model_name='mfanotification',
            index=models.Index(fields=['expires_at'], name='mfa_notific_expires_fb26e9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['user', 'status'], name='email_notif_user_id_6b5e93_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['email_type', 'status'], name='email_notif_email_t_f26f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['-created_at'], name='email_notif_created_6edd9d_idx'),
        ),
        migrations.AddIndex(
            model_name='detailednotificationpreference',
            index=models.Index(fields=['user', 'notification_type'], name='detailed_no_user_id_fb1e10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='detailednotificationpreference',
            unique_together={('user', 'notification_type')},
        ),
    ]
