# Generated by Django 4.2 on 2026-01-06 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('browser_version', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_trusted', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('trust_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_used_at', models.DateTimeField(auto_now_add=True)),
                ('total_logins', models.PositiveIntegerField(default=0)),
                ('is_compromised', models.BooleanField(db_index=True, default=False)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('last_risk_assessment', models.DateTimeField(blank=True, null=True)),
                ('can_skip_mfa', models.BooleanField(default=False)),
                ('mfa_skip_until', models.DateTimeField(blank=True, null=True)),
                ('security_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('trust_days', models.PositiveIntegerField(default=30)),
                ('is_trusted', models.BooleanField(default=True)),
                ('trusted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('times_skipped_mfa', models.PositiveIntegerField(default=0)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_records', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'db_table': 'trusted_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'is_trusted'], name='trusted_dev_user_id_37dbbc_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['expires_at'], name='trusted_dev_expires_cd22b8_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_trusted', 'is_deleted'], name='devices_user_id_fad56c_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_verified'], name='devices_user_id_beffe9_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['fingerprint_hash'], name='devices_fingerp_09968a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['last_used_at'], name='devices_last_us_09d796_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_compromised'], name='devices_is_comp_642b15_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['risk_score'], name='devices_risk_sc_cdcbd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'fingerprint_hash')},
        ),
    ]
