# Generated by Django 4.2 on 2026-01-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_session_session_sessions_user_id_85103c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fingerprint_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
