# Generated by Django 4.2 on 2026-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_mfa_backup_codes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mfa_backup_codes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_method',
            field=models.CharField(choices=[('totp', 'TOTP'), ('email', 'Email'), ('sms', 'SMS')], default='totp', max_length=20),
        ),
    ]
